### ISSUE TITLE
Compatible WHMCS and PHP Versions ?

### ISSUE THREAD

**Issue by ProTechEx** [ugurterzi/iyzipay#1]
Hi Ugur,

which WHMCS and PHP Versions are supported ?
Could add support for EUR currency please ?

Thanks and Regards.

Özgür

**Comment by ugurterzi** [comment]
Hi Ozgur, we're currently using with Version: 7.7.1 right now (PHP 7.2)
Regarding the EUR currency, I'm planning to add that very soon.

**Comment by ProTechEx** [comment]
Hey Ugur,

wow, thanks for the fast reply.

And as I know, Iyzico does update theier API some time ago. Does your module also up to date with the new API ?

**Comment by ugurterzi** [comment]
Yes, it is. Actually, iyzipay api php client is pretty same as from 3 years from now :)
https://github.com/iyzico/iyzipay-php
You should test and report the bugs here (if any). I and @milosmweb are always ready to fix.

**Comment by ProTechEx** [comment]
I would use your Module, but as I said i need also Eur support. Can you say approximately when you will add euro support ?

**Comment by ugurterzi** [comment]
I checked, so, Multi-Currency is a module that you need to make enable from iyzico merchant panel. Then you can use our module with whatever (I am sure iyzico supports euro) currency you want.

**Comment by ProTechEx** [comment]
That’s realy cool, thanks for the info.
