### ISSUE TITLE
Remote Storage Failed

### ISSUE THREAD

**Issue by ProTechEx** [ugurterzi/iyzipay#3]
Debug Data:

**Comment by ProTechEx** [comment]
UserID => 99
{"status":"failure","errorCode":"3007","errorMessage":"Card storage feature is not enabled for this merchant","locale":"en","systemTime":1555904546990,"conversationId":"StreaXXXXXXXers","email":"maxx@xxxx.fr"}

**Comment by ugurterzi** [comment]
I think the error message says what you need to fix in here: Card storage feature is not enabled for this merchant. That means you should log in to your iyzico merchant account and enable the Card storage feature.
/ Or, you might want to enable "Disable Credit Card Storage" via WHMCS > admin > setup > general settings > security
