### ISSUE TITLE
Module Cron Job İssue

### ISSUE THREAD

**Issue by ProTechEx** [ugurterzi/iyzipay#5]
Hi,

i get an issue when i try to run the cron Job:

```
[root@srv01 ~]# php -q /home/streamingservers/public_html/crons/cron.php -vvv --                                                                                                                                                             force all

WHMCS Automation Task Utility: all
==================================

 Daily Cron Automation Mode

Queuing Tasks
-------------

 Force run any tasks: ignore "in progress" and "is due"
 Task queues ready

Executing Application Queue
---------------------------

  0/26 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0% < 1 sec/< 1 sec 24.0 MiB
 Currency Exchange Rates
  1/26 [▓░░░░░░░░░░░░░░░░░░░░░░░░░░░]   3% < 1 sec/< 1 sec 24.0 MiB
 Product Pricing Updates
  2/26 [▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░]   7% < 1 sec/< 1 sec 24.0 MiB
 Invoices
  3/26 [▓▓▓░░░░░░░░░░░░░░░░░░░░░░░░░]  11%  1 sec/9 secs 24.0 MiB
 Late Fees
  4/26 [▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░░]  15%  1 sec/7 secs 24.0 MiB
 Credit Card Charges
  5/26 [▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░]  19% 2 secs/10 secs 28.0 MiB<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Oops!</title>

<style>
        body {
            margin: 30px 40px;
            background-color: #f6f6f6;
        }
        .error-container {
            padding: 50px 40px;
            font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
            font-size: 14px;
        }
        h1 {
            margin: 0;
            font-size: 48px;
            font-weight: 400;
        }
        h2 {
            margin: 0;
            font-size: 26px;
            font-weight: 300;
        }
        a {
            color: #336699;
        }
        p.back-to-home {
            margin-top: 30px;
        }
        p.debug{
            padding: 20px 0;
            font-family: "Courier New", Courier, monospace, serif;
            font-size: 14px;
        }
        .info {
            border: solid 1px #999;
            padding: 5px;
            background-color: #d9edf7;
        }
    </style>

  </head>
  <body>
    <div class="error-container">
<h1>Oops!</h1>
<h2>Something went wrong and we couldn't process your request.</h2>
<p>Please go back to the previous page and try again.</p>
<p class="debug">ArgumentCountError: Too few arguments to function logModuleCall(), 3 passed in /home/streamingservers/public_html/modules/gateways/iyzipay/index.php on line 446 and at least 4 expected in /home/streamingservers/public_html/includes/functions.php:0<br />
Stack trace:<br />
#0 /home/streamingservers/public_html/modules/gateways/iyzipay/index.php(446): logModuleCall('iyzipay', 'requestobject', Array)<br />
#1 /home/streamingservers/public_html/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): iyzipay_capture(Array)<br />
#2 /home/streamingservers/public_html/vendor/whmcs/whmcs-foundation/lib/Module/Gateway.php(0): WHMCS\Module\AbstractModule->call('capture', Array)<br />
#3 /home/streamingservers/public_html/includes/ccfunctions.php(0): WHMCS\Module\Gateway->call('capture', Array)<br />
#4 /home/streamingservers/public_html/includes/ccfunctions.php(0): captureCCPayment(1368)<br />
#5 /home/streamingservers/public_html/vendor/whmcs/whmcs-foundation/lib/Cron/Task/ProcessCreditCardPayments.php(0): ccProcessing(Object(WHMCS\Cron\Task\ProcessCreditCardPayments))<br />
#6 /home/streamingservers/public_html/vendor/whmcs/whmcs-foundation/lib/Scheduling/Task/AbstractTask.php(0): WHMCS\Cron\Task\ProcessCreditCardPayments->__invoke()<br />
#7 /home/streamingservers/public_html/vendor/whmcs/whmcs-foundation/lib/Scheduling/Task/AbstractTask.php(0): WHMCS\Scheduling\Task\AbstractTask->execute()<br />
#8 /home/streamingservers/public_html/vendor/whmcs/whmcs-foundation/lib/Cron/Console/Command/AbstractCronCommand.php(0): WHMCS\Scheduling\Task\AbstractTask->run()<br />
#9 /home/streamingservers/public_html/vendor/whmcs/whmcs-foundation/lib/Cron/Console/Command/AbstractCronCommand.php(0): WHMCS\Cron\Console\Command\AbstractCronCommand->executeCollection(Object(WHMCS\Scheduling\Task\Collection))<br />
#10 /home/streamingservers/public_html/vendor/symfony/console/Command/Command.php(259): WHMCS\Cron\Console\Command\AbstractCronCommand->execute(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput))<br />
#11 /home/streamingservers/public_html/vendor/symfony/console/Application.php(844): Symfony\Component\Console\Command\Command->run(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput))<br />
#12 /home/streamingservers/public_html/vendor/symfony/console/Application.php(192): Symfony\Component\Console\Application->doRunCommand(Object(WHMCS\Cron\Console\Command\AllCommand), Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput))<br />
#13 /home/streamingservers/public_html/vendor/symfony/console/Application.php(123): Symfony\Component\Console\Application->doRun(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput))<br />
#14 /home/streamingservers/public_html/crons/cron.php(0): Symfony\Component\Console\Application->run(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput))<br />
#15 {main}</p></div>
  </body>
</html>[root@srv01 ~]# ^C
```
I just update my PHP Version to 7.2 and i am running WHMCS 7.6.1
Is it possible that Gateway is not compatible with PHP 7.2 and WHMCS 7.6.1

If not could update the coder please ?

Thanks in advance.

**Comment by ugurterzi** [comment]
It is working perfectly fine with PHP 7.2. We're using it on our own without any trouble. (https://merll.triceps.com.tr/clientarea.php)

**Comment by ProTechEx** [comment]
Thanks for your reply Ugur.
Do you have any Idea, why the issue appears once the daily cron job is running?

How can i fix it?

**Comment by ugurterzi** [comment]
As you know WHMCS is not an open source software so, functions.php is an encrypted file. That means I can not see the arguments right now. The better way for you to ask this to WHMCS team and share their reply with me. I will be happy to help

**Comment by homer48** [comment]
> Hi,
> 
> i get an issue when i try to run the cron Job:
> 
> ```
> [root@srv01 ~]# php -q /home/streamingservers/public_html/crons/cron.php -vvv --                                                                                                                                                             force all
> 
> WHMCS Automation Task Utility: all
> ==================================
> 
>  Daily Cron Automation Mode
> 
> Queuing Tasks
> -------------
> 
>  Force run any tasks: ignore "in progress" and "is due"
>  Task queues ready
> 
> Executing Application Queue
> ---------------------------
> 
>   0/26 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0% < 1 sec/< 1 sec 24.0 MiB
>  Currency Exchange Rates
>   1/26 [▓░░░░░░░░░░░░░░░░░░░░░░░░░░░]   3% < 1 sec/< 1 sec 24.0 MiB
>  Product Pricing Updates
>   2/26 [▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░]   7% < 1 sec/< 1 sec 24.0 MiB
>  Invoices
>   3/26 [▓▓▓░░░░░░░░░░░░░░░░░░░░░░░░░]  11%  1 sec/9 secs 24.0 MiB
>  Late Fees
>   4/26 [▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░░]  15%  1 sec/7 secs 24.0 MiB
>  Credit Card Charges
>   5/26 [▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░]  19% 2 secs/10 secs 28.0 MiB<!DOCTYPE html>
> <html lang="en">
>   <head>
>     <meta charset="utf-8">
>     <meta http-equiv="X-UA-Compatible" content="IE=edge">
>     <meta name="viewport" content="width=device-width, initial-scale=1">
>     <title>Oops!</title>
> 
> <style>
>         body {
>             margin: 30px 40px;
>             background-color: #f6f6f6;
>         }
>         .error-container {
>             padding: 50px 40px;
>             font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
>             font-size: 14px;
>         }
>         h1 {
>             margin: 0;
>             font-size: 48px;
>             font-weight: 400;
>         }
>         h2 {
>             margin: 0;
>             font-size: 26px;
>             font-weight: 300;
>         }
>         a {
>             color: #336699;
>         }
>         p.back-to-home {
>             margin-top: 30px;
>         }
>         p.debug{
>             padding: 20px 0;
>             font-family: "Courier New", Courier, monospace, serif;
>             font-size: 14px;
>         }
>         .info {
>             border: solid 1px #999;
>             padding: 5px;
>             background-color: #d9edf7;
>         }
>     </style>
> 
>   </head>
>   <body>
>     <div class="error-container">
> <h1>Oops!</h1>
> <h2>Something went wrong and we couldn't process your request.</h2>
> <p>Please go back to the previous page and try again.</p>
> <p class="debug">ArgumentCountError: Too few arguments to function logModuleCall(), 3 passed in /home/streamingservers/public_html/modules/gateways/iyzipay/index.php on line 446 and at least 4 expected in /home/streamingservers/public_html/includes/functions.php:0<br />
> Stack trace:<br />
> #0 /home/streamingservers/public_html/modules/gateways/iyzipay/index.php(446): logModuleCall('iyzipay', 'requestobject', Array)<br />
> #1 /home/streamingservers/public_html/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): iyzipay_capture(Array)<br />
> #2 /home/streamingservers/public_html/vendor/whmcs/whmcs-foundation/lib/Module/Gateway.php(0): WHMCS\Module\AbstractModule->call('capture', Array)<br />
> #3 /home/streamingservers/public_html/includes/ccfunctions.php(0): WHMCS\Module\Gateway->call('capture', Array)<br />
> #4 /home/streamingservers/public_html/includes/ccfunctions.php(0): captureCCPayment(1368)<br />
> #5 /home/streamingservers/public_html/vendor/whmcs/whmcs-foundation/lib/Cron/Task/ProcessCreditCardPayments.php(0): ccProcessing(Object(WHMCS\Cron\Task\ProcessCreditCardPayments))<br />
> #6 /home/streamingservers/public_html/vendor/whmcs/whmcs-foundation/lib/Scheduling/Task/AbstractTask.php(0): WHMCS\Cron\Task\ProcessCreditCardPayments->__invoke()<br />
> #7 /home/streamingservers/public_html/vendor/whmcs/whmcs-foundation/lib/Scheduling/Task/AbstractTask.php(0): WHMCS\Scheduling\Task\AbstractTask->execute()<br />
> #8 /home/streamingservers/public_html/vendor/whmcs/whmcs-foundation/lib/Cron/Console/Command/AbstractCronCommand.php(0): WHMCS\Scheduling\Task\AbstractTask->run()<br />
> #9 /home/streamingservers/public_html/vendor/whmcs/whmcs-foundation/lib/Cron/Console/Command/AbstractCronCommand.php(0): WHMCS\Cron\Console\Command\AbstractCronCommand->executeCollection(Object(WHMCS\Scheduling\Task\Collection))<br />
> #10 /home/streamingservers/public_html/vendor/symfony/console/Command/Command.php(259): WHMCS\Cron\Console\Command\AbstractCronCommand->execute(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput))<br />
> #11 /home/streamingservers/public_html/vendor/symfony/console/Application.php(844): Symfony\Component\Console\Command\Command->run(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput))<br />
> #12 /home/streamingservers/public_html/vendor/symfony/console/Application.php(192): Symfony\Component\Console\Application->doRunCommand(Object(WHMCS\Cron\Console\Command\AllCommand), Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput))<br />
> #13 /home/streamingservers/public_html/vendor/symfony/console/Application.php(123): Symfony\Component\Console\Application->doRun(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput))<br />
> #14 /home/streamingservers/public_html/crons/cron.php(0): Symfony\Component\Console\Application->run(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput))<br />
> #15 {main}</p></div>
>   </body>
> </html>[root@srv01 ~]# ^C
> ```
> 
> I just update my PHP Version to 7.2 and i am running WHMCS 7.6.1
> Is it possible that Gateway is not compatible with PHP 7.2 and WHMCS 7.6.1
> 
> If not could update the coder please ?
> 
> Thanks in advance.

Hi, I'm having this problem. did you solve the problem?

**Comment by ugurterzi** [comment]
As I mentioned before, ask this to WHMCS first. Because we have no such error on our end.
