### ISSUE TITLE
Invalid invoice id provided

### ISSUE THREAD

**Issue by baykalerol** [ugurterzi/iyzipay#6]
whmcs 7.9.1'de iyzipay test modunda herşey sorunsuz. Fakat canlıya alındığında 3ds ekranındayken Error: Invalid invoice id provided hatası alınıyor. sayfa url ise; /viewinvoice.php?id=&paymentfailed=true şeklinde.

iyzico tarafında işlem kaydediliyor 3ds tarafı başlamadığı/tamamlanamadığı için 3Ds Üye İşyerine Dönüldü durumunda işlem bekliyor.

![111](https://user-images.githubusercontent.com/22080040/74580639-5ad8f980-4fb7-11ea-8364-02c93244313e.PNG)

**Comment by ugurterzi** [comment]
Reporting enable edip log bakmak lazım. https://docs.whmcs.com/Enabling_Error_Reporting
Paylaşabilir misiniz.

**Comment by baykalerol** [comment]
InvalidArgumentException: No Local Credit Card Payment Gateways Enabled in /var/www/website.com/public_html/vendor/whmcs/whmcs-foundation/lib/Payment/PayMethod/Adapter/CreditCard.php:0

**Comment by baykalerol** [comment]
function iyzipay_MetaData()
{
    return array(
        'DisplayName' => 'Iyzipay Merchant Gateway Module',
        'APIVersion' => '1.1', // Use API Version 1.1
        'DisableLocalCredtCardInput' => false,
        'TokenisedStorage' => true,
    );
}

**Comment by ugurterzi** [comment]
If I am not wrong, it is a bug of WHMCS not related to this module. Do you run on the latest version?
Eğer yanılmıyorsam bu bir WHMCS hatası ve bizim modul ile ilegili değil. WHMCS en son sürümde mi şu an? Güncel mi? Bu arada aşağıdaki linki inceleminizde fayda var.
Please check https://whmcs.community/files/file/126-module-7252-no-local-credit-card-payment-gateways-enabled-error-on-reference-gateways/

**Comment by baykalerol** [comment]
7.9.2 versiyona güncellemiştim. Bu hotfixi denedim ancak durum değişmemişti. whmcs üzerinden ticket açayım, geri dönüşlerine göre tekrar yazarım. teşekkürler.

**Comment by ugurterzi** [comment]
Sorun devam ederse lütfen issuu'yu güncelleyin.
